parsers:
  - name: LegacyCXXParser
    package: '@agoraio-extensions/terra-legacy-cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/AgoraRefPtr.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/AgoraOptional.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/AgoraRefPtr.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/IAgoraH265Transcoder.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/IAgoraMediaComponentFactory.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/include/IAgoraParameter.h'
      customHeaders:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.2.x.cx_sp/custom_headers/*.h'
      language: ts
      definesMacros:
        - __ELECTRON__
      legacyRenders:
        - TsInterfaceRender
        - TsImplRender
