/*
 * @Author: zhangtao@agora.io
 * @Date: 2021-04-22 11:36:26
 * @Last Modified by: zhangtao@agora.io
 * @Last Modified time: 2021-05-11 11:59:59
 */

export enum ApiTypeEngine {
  kEngineInitialize,
  kEngineRelease,
  kEngineSetChannelProfile,
  kEngineSetClientRole,
  kEngineJoinChannel,
  kEngineSwitchChannel,
  kEngineLeaveChannel,
  kEngineRenewToken,
  kEngineRegisterLocalUserAccount,
  kEngineJoinChannelWithUserAccount,
  kEngineGetUserInfoByUserAccount,
  kEngineGetUserInfoByUid,
  kEngineStartEchoTest,
  kEngineStopEchoTest,
  kEngineSetCloudProxy,
  kEngineEnableVideo,
  kEngineDisableVideo,
  kEngineSetVideoProfile,
  kEngineSetVideoEncoderConfiguration,
  kEngineSetCameraCapturerConfiguration,
  kEngineSetupLocalVideo,
  kEngineSetupRemoteVideo,
  kEngineStartPreview,
  kEngineSetRemoteUserPriority,
  kEngineStopPreview,
  kEngineEnableAudio,
  kEngineEnableLocalAudio,
  kEngineDisableAudio,
  kEngineSetAudioProfile,
  kEngineMuteLocalAudioStream,
  kEngineMuteAllRemoteAudioStreams,
  kEngineSetDefaultMuteAllRemoteAudioStreams,
  kEngineAdjustUserPlaybackSignalVolume,
  kEngineMuteRemoteAudioStream,
  kEngineMuteLocalVideoStream,
  kEngineEnableLocalVideo,
  kEngineMuteAllRemoteVideoStreams,
  kEngineSetDefaultMuteAllRemoteVideoStreams,
  kEngineMuteRemoteVideoStream,
  kEngineSetRemoteVideoStreamType,
  kEngineSetRemoteDefaultVideoStreamType,
  kEngineEnableAudioVolumeIndication,
  kEngineStartAudioRecording,
  kEngineStopAudioRecording,
  kEngineStartAudioMixing,
  kEngineStopAudioMixing,
  kEnginePauseAudioMixing,
  kEngineResumeAudioMixing,
  kEngineSetHighQualityAudioParameters,
  kEngineAdjustAudioMixingVolume,
  kEngineAdjustAudioMixingPlayoutVolume,
  kEngineGetAudioMixingPlayoutVolume,
  kEngineAdjustAudioMixingPublishVolume,
  kEngineGetAudioMixingPublishVolume,
  kEngineGetAudioMixingDuration,
  kEngineGetAudioMixingCurrentPosition,
  kEngineSetAudioMixingPosition,
  kEngineSetAudioMixingPitch,
  kEngineGetEffectsVolume,
  kEngineSetEffectsVolume,
  kEngineSetVolumeOfEffect,
  kEngineEnableFaceDetection,
  kEnginePlayEffect,
  kEngineStopEffect,
  kEngineStopAllEffects,
  kEnginePreloadEffect,
  kEngineUnloadEffect,
  kEnginePauseEffect,
  kEnginePauseAllEffects,
  kEngineResumeEffect,
  kEngineResumeAllEffects,
  kEngineGetEffectDuration,
  kEngineSetEffectPosition,
  kEngineGetEffectCurrentPosition,
  kEngineEnableDeepLearningDenoise,
  kEngineEnableSoundPositionIndication,
  kEngineSetRemoteVoicePosition,
  kEngineSetLocalVoicePitch,
  kEngineSetLocalVoiceEqualization,
  kEngineSetLocalVoiceReverb,
  kEngineSetLocalVoiceChanger,
  kEngineSetLocalVoiceReverbPreset,
  kEngineSetVoiceBeautifierPreset,
  kEngineSetAudioEffectPreset,
  kEngineSetVoiceConversionPreset,
  kEngineSetAudioEffectParameters,
  kEngineSetVoiceBeautifierParameters,
  kEngineSetLogFile,
  kEngineSetLogFilter,
  kEngineSetLogFileSize,
  kEngineUploadLogFile,
  kEngineSetLocalRenderMode,
  kEngineSetRemoteRenderMode,
  kEngineSetLocalVideoMirrorMode,
  kEngineEnableDualStreamMode,
  kEngineSetExternalAudioSource,
  kEngineSetExternalAudioSink,
  kEngineSetRecordingAudioFrameParameters,
  kEngineSetPlaybackAudioFrameParameters,
  kEngineSetMixedAudioFrameParameters,
  kEngineAdjustRecordingSignalVolume,
  kEngineAdjustPlaybackSignalVolume,
  kEngineAdjustLoopBackRecordingSignalVolume,
  kEngineEnableWebSdkInteroperability,
  kEngineSetVideoQualityParameters,
  kEngineSetLocalPublishFallbackOption,
  kEngineSetRemoteSubscribeFallbackOption,
  kEngineSwitchCamera,
  kEngineSetDefaultAudioRouteToSpeakerPhone,
  kEngineSetEnableSpeakerPhone,
  kEngineEnableInEarMonitoring,
  kEngineSetInEarMonitoringVolume,
  kEngineIsSpeakerPhoneEnabled,
  kEngineSetAudioSessionOperationRestriction,
  kEngineEnableLoopBackRecording,
  kEngineStartScreenCaptureByDisplayId,
  kEngineStartScreenCaptureByScreenRect,
  kEngineStartScreenCaptureByWindowId,
  kEngineSetScreenCaptureContentHint,
  kEngineUpdateScreenCaptureParameters,
  kEngineUpdateScreenCaptureRegion,
  kEngineStopScreenCapture,
  kEngineStartScreenCapture,
  kEngineSetVideoSource,
  kEngineGetCallId,
  kEngineRate,
  kEngineComplain,
  kEngineGetVersion,
  kEngineEnableLastMileTest,
  kEngineDisableLastMileTest,
  kEngineStartLastMileProbeTest,
  kEngineStopLastMileProbeTest,
  kEngineGetErrorDescription,
  kEngineSetEncryptionSecret,
  kEngineSetEncryptionMode,
  kEngineEnableEncryption,
  kEngineRegisterPacketObserver,
  kEngineCreateDataStream,
  kEngineSendStreamMessage,
  kEngineAddPublishStreamUrl,
  kEngineRemovePublishStreamUrl,
  kEngineSetLiveTranscoding,
  kEngineAddVideoWaterMark,
  kEngineClearVideoWaterMarks,
  kEngineSetBeautyEffectOptions,
  kEngineEnableVirtualBackground,
  kEngineAddInjectStreamUrl,
  kEngineStartChannelMediaRelay,
  kEngineUpdateChannelMediaRelay,
  kEnginePauseAllChannelMediaRelay,
  kEngineResumeAllChannelMediaRelay,
  kEngineStopChannelMediaRelay,
  kEngineRemoveInjectStreamUrl,
  kEngineSendCustomReportMessage,
  kEngineGetConnectionState,
  kEngineEnableRemoteSuperResolution,
  kEngineRegisterMediaMetadataObserver,
  kEngineSetParameters,
  kEngineSetLocalAccessPoint,
  kEngineUnRegisterMediaMetadataObserver,
  kEngineSetMaxMetadataSize,
  kEngineSendMetadata,
  kEngineSetAppType,
  kMediaPushAudioFrame,
  kMediaPullAudioFrame,
  kMediaSetExternalVideoSource,
  kMediaPushVideoFrame,
  kEngineSetAudioMixingPlaybackSpeed,
  kEngineSelectAudioTrack,
  kEngineGetAudioTrackCount,
  kEngineSetAudioMixingDualMonoMode,
  kEngineGetAudioFileInfo,
  kEngineSetVideoProfileEx,
  kMediaSetExternalAudioSourceVolume,
  kEngineSetLogWriter,
  kEngineReleaseLogWriter,
  kEngineSetLocalVideoRenderer,
  kEngineSetRemoteVideoRenderer,
  kEngineSetCameraTorchOn,
  kEngineIsCameraTorchSupported,
  kEngineGetCameraMaxZoomFactor,
  kEngineIsCameraAutoFocusFaceModeSupported,
  kEngineIsCameraExposurePositionSupported,
  kEngineIsCameraFocusSupported,
  kEngineIsCameraZoomSupported,
  kEngineSetCameraAutoFocusFaceModeEnabled,
  kEngineSetCameraExposurePosition,
  kEngineSetCameraFocusPositionInPreview,
  kEngineSetCameraZoomFactor,
  kEngineStartRhythmPlayer,
  kEngineStopRhythmPlayer,
  kEngineConfigRhythmPlayer,
  kEngineGetNativeHandle,
  kEngineGetScreenCaptureSources,
  kEngineTakeSnapshot,
  kEngineEnableContentInspect,
}

export enum ApiTypeChannel {
  kChannelCreateChannel = 0,
  kChannelRelease = 1,
  kChannelJoinChannel = 2,
  kChannelJoinChannelWithUserAccount = 3,
  kChannelLeaveChannel = 4,
  kChannelPublish = 5,
  kChannelUnPublish = 6,
  kChannelChannelId = 7,
  kChannelGetCallId = 8,
  kChannelRenewToken = 9,
  kChannelSetEncryptionSecret = 10,
  kChannelSetEncryptionMode = 11,
  kChannelEnableEncryption = 12,
  kChannelRegisterPacketObserver = 13,
  kChannelRegisterMediaMetadataObserver = 14,
  kChannelUnRegisterMediaMetadataObserver = 15,
  kChannelSetMaxMetadataSize = 16,
  kChannelSendMetadata = 17,
  kChannelSetClientRole = 18,
  kChannelSetRemoteUserPriority = 19,
  kChannelSetRemoteVoicePosition = 20,
  kChannelSetRemoteRenderMode = 21,
  kChannelSetDefaultMuteAllRemoteAudioStreams = 22,
  kChannelSetDefaultMuteAllRemoteVideoStreams = 23,
  kChannelMuteLocalAudioStream = 24,
  kChannelMuteLocalVideoStream = 25,
  kChannelMuteAllRemoteAudioStreams = 26,
  kChannelAdjustUserPlaybackSignalVolume = 27,
  kChannelMuteRemoteAudioStream = 28,
  kChannelMuteAllRemoteVideoStreams = 29,
  kChannelMuteRemoteVideoStream = 30,
  kChannelSetRemoteVideoStreamType = 31,
  kChannelSetRemoteDefaultVideoStreamType = 32,
  kChannelCreateDataStream = 33,
  kChannelSendStreamMessage = 34,
  kChannelAddPublishStreamUrl = 35,
  kChannelRemovePublishStreamUrl = 36,
  kChannelSetLiveTranscoding = 37,
  kChannelAddInjectStreamUrl = 38,
  kChannelRemoveInjectStreamUrl = 39,
  kChannelStartChannelMediaRelay = 40,
  kChannelUpdateChannelMediaRelay = 41,
  kChannelPauseAllChannelMediaRelay = 42,
  kChannelResumeAllChannelMediaRelay = 43,
  kChannelStopChannelMediaRelay = 44,
  kChannelGetConnectionState = 45,
  kChannelEnableRemoteSuperResolution = 46,
}

export enum ApiTypeAudioDeviceManager {
  kADMEnumeratePlaybackDevices = 0,
  kADMSetPlaybackDevice = 1,
  kADMGetPlaybackDevice = 2,
  kADMGetPlaybackDeviceInfo = 3,
  kADMSetPlaybackDeviceVolume = 4,
  kADMGetPlaybackDeviceVolume = 5,
  kADMSetPlaybackDeviceMute = 6,
  kADMGetPlaybackDeviceMute = 7,
  kADMStartPlaybackDeviceTest = 8,
  kADMStopPlaybackDeviceTest = 9,
  kADMEnumerateRecordingDevices = 10,
  kADMSetRecordingDevice = 11,
  kADMGetRecordingDevice = 12,
  kADMGetRecordingDeviceInfo = 13,
  kADMSetRecordingDeviceVolume = 14,
  kADMGetRecordingDeviceVolume = 15,
  kADMSetRecordingDeviceMute = 16,
  kADMGetRecordingDeviceMute = 17,
  kADMStartRecordingDeviceTest = 18,
  kADMStopRecordingDeviceTest = 19,
  kADMStartAudioDeviceLoopbackTest = 20,
  kADMStopAudioDeviceLoopbackTest = 21,
}

export enum ApiTypeVideoDeviceManager {
  kVDMEnumerateVideoDevices = 0,
  kVDMSetDevice = 1,
  kVDMGetDevice = 2,
  kVDMStartDeviceTest = 3,
  kVDMStopDeviceTest = 4,
}

export enum ApiTypeRawDataPluginManager {
  kRDPMRegisterPlugin = 0,
  kRDPMUnregisterPlugin = 1,
  kRDPMHasPlugin = 2,
  kRDPMEnablePlugin = 3,
  kRDPMGetPlugins = 4,
  kRDPMSetPluginParameter = 5,
  kRDPMGetPluginParameter = 6,
  kRDPMRelease = 7,
}

export enum PROCESS_TYPE {
  MAIN,
  SCREEN_SHARE,
}

export interface Result {
  retCode: number;
  result: string;
}

export enum VOICE_CONVERSION_PRESET {
  /** Turn off voice conversion effects and use the original voice.
   */
  VOICE_CONVERSION_OFF = 0x00000000,
  /** A gender-neutral voice. To avoid audio distortion, ensure that you use
   * this enumerator to process a female-sounding voice.
   */
  VOICE_CHANGER_NEUTRAL = 0x03010100,
  /** A sweet voice. To avoid audio distortion, ensure that you use this
   * enumerator to process a female-sounding voice.
   */
  VOICE_CHANGER_SWEET = 0x03010200,
  /** A steady voice. To avoid audio distortion, ensure that you use this
   * enumerator to process a male-sounding voice.
   */
  VOICE_CHANGER_SOLID = 0x03010300,
  /** A deep voice. To avoid audio distortion, ensure that you use this
   * enumerator to process a male-sounding voice.
   */
  VOICE_CHANGER_BASS = 0x03010400,
}

export interface SIZE {
  width: number;
  height: number;
}

export enum AUDIO_MIXING_DUAL_MONO_MODE {
  /**
   * 0: Original mode.
   */
  AUDIO_MIXING_DUAL_MONO_AUTO = 0,
  /**
   * 1: Left channel mode. This mode replaces the audio of the right channel
   * with the audio of the left channel, which means the user can only hear
   * the audio of the left channel.
   */
  AUDIO_MIXING_DUAL_MONO_L = 1,
  /**
   * 2: Right channel mode. This mode replaces the audio of the left channel with
   * the audio of the right channel, which means the user can only hear the audio
   * of the right channel.
   */
  AUDIO_MIXING_DUAL_MONO_R = 2,
  /**
   * 3: Mixed channel mode. This mode mixes the audio of the left channel and
   * the right channel, which means the user can hear the audio of the left
   * channel and the right channel at the same time.
   */
  AUDIO_MIXING_DUAL_MONO_MIX = 3,
}
export enum IrisVideoSourceType {
  kVideoSourceTypeCameraPrimary,
  kVideoSourceTypeCameraSecondary,
  kVideoSourceTypeScreenPrimary,
  kVideoSourceTypeScreenSecondary,
  kVideoSourceTypeCustom,
  kVideoSourceTypeMediaPlayer,
  kVideoSourceTypeRtcImagePng,
  kVideoSourceTypeRtcImageJpeg,
  kVideoSourceTypeRtcImageGif,
  kVideoSourceTypeRemote,
  kVideoSourceTypeTranscoded,
  kVideoSourceTypeUnknown,
}
