name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v14.17.3

    - name: Setup Yarn
      run:
        npm i -g yarn@1.22.19
      shell: bash

    - name: Remove .npmrc
      run: |
        rm -f .npmrc
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.5

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-yarn-ng-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-ng

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
      shell: bash
