name: Setup
description: Setup Node.js and install dependencies
inputs:
  skip_install:
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Setup Yarn
      run: npm i -g yarn@1.22.19
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.5

    - name: Install dependencies
      if: ${{ inputs.skip_install == 'false' }}
      run: |
        yarn config set agora-electron-sdk-pre-built 0
        yarn install --frozen-lockfile
        yarn patch-package
      shell: bash
