name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.17.3

    - name: Remove .npmrc
      run: |
        rm -f .npmrc
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        npm install
      shell: bash
