export enum EngineEvents {
  API_ERROR = "apiError",
  WARNING = "warning",
  ERROR = "error",
  /**
   * @deprecated
   */
  JOINED_CHANNEL = "joinedChannel",
  /**
   * @deprecated
   */
  JOINEDCHANNEL = "joinedchannel",
  REJOIN_CHANNEL_SUCCESS = "rejoinChannelSuccess",
  REJOINCHANNELSUCCESS = "rejoinchannelsuccess",
  LEAVE_CHANNEL = "leaveChannel",
  /**
   * @deprecated
   */
  LEAVECHANNEL = "leavechannel",
  CLIENT_ROLE_CHANGED = "clientRoleChanged",
  /**
   * @deprecated
   */
  CLIENTROLECHANGED = "clientrolechanged",
  USER_JOINED = "userJoined",
  /**
   * @deprecated
   */
  USERJOINED = "userjoined",
  USER_OFFLINE = "userOffline",
  REMOVE_STREAM = "removeStream",
  /**
   * @deprecated
   */
  LASTMILEQUALITY = "lastmilequality",
  LASTMILE_QUALITY = "lastmileQuality",
  LASTMILE_PROBE_RESULT = "lastmileProbeResult",
  LASTMILEPROBERESULT = "lastmileproberesult",
  CONNECTIONINTERRUPTED = "connectioninterrupted",
  CONNECTION_INTERRUPTED = "connectionInterrupted",
  CONNECTIONLOST = "connectionlost",
  CONNECTION_LOST = "connectionLost",
  CONNECTIONBANNED = "connectionbanned",
  CONNECTION_BANNED = "connectionBanned",
  API_CALL_EXECUTED = "apiCallExecuted",
  APICALLEXECUTED = "apicallexecuted",
  REQUEST_TOKEN = "requestToken",
  TOKEN_PRIVILEGE_WILL_EXPIRE = "tokenPrivilegeWillExpire",
  AUDIO_QUALITY = "audioQuality",
  RTCSTATS = "rtcstats",
  RTC_STATS = "rtcStats",
  NETWORKQUALITY = "networkquality",
  NETWORK_QUALITY = "networkQuality",
  LOCAL_VIDEO_STATS = "localVideoStats",
  REMOTE_VIDEO_STATS = "remoteVideoStats",
  LOCAL_AUDIO_STATS = "localAudioStats",
  REMOTE_AUDIO_STATS = "remoteAudioStats",
  LOCAL_AUDIO_STATE_CHANGED = "localAudioStateChanged",
  REMOTE_AUDIO_STATE_CHANGED = "remoteAudioStateChanged",
  AUDIO_PUBLISH_STATE_CHANGED = "audioPublishStateChanged",
  VIDEO_PUBLISH_STATE_CHANGED = "videoPublishStateChanged",
  AUDIO_SUBSCRIBE_STATE_CHANGED = "audioSubscribeStateChanged",
  VIDEO_SUBSCRIBE_STATE_CHANGED = "videoSubscribeStateChanged",
  AUDIO_VOLUME_INDICATION = "audioVolumeIndication",
  GROUP_AUDIO_VOLUME_INDICATION = "groupAudioVolumeIndication",
  ACTIVE_SPEAKER = "activeSpeaker",
  VIDEOSTOPPED = "videostopped",
  VIDEO_STOPPED = "videoStopped",
  FIRST_LOCAL_VIDEO_FRAME = "firstLocalVideoFrame",
  FIRST_REMOTE_VIDEO_FRAME = "firstRemoteVideoFrame",
  FIRST_LOCAL_VIDEO_FRAME_PUBLISHED = "firstLocalVideoFramePublished",
  USERMUTEAUDIO = "usermuteaudio",
  USER_MUTE_AUDIO = "userMuteAudio",
  USERMUTEVIDEO = "usermutevideo",
  USER_MUTE_VIDEO = "userMuteVideo",
  USERENABLEVIDEO = "userenablevideo",
  USER_ENABLE_VIDEO = "userEnableVideo",
  AUDIODEVICESTATECHANGED = "audiodevicestatechanged",
  AUDIO_DEVICE_STATE_CHANGED = "audioDeviceStateChanged",
  AUDIODEVICEVOLUMECHANGED = "audiodevicevolumechanged",
  AUDIO_DEVICE_VOLUME_CHANGED = "audioDeviceVolumeChanged",
  CAMERAREADY = "cameraready",
  CAMERA_READY = "cameraReady",
  CAMERA_FOCUS_AREA_CHANGED = "cameraFocusAreaChanged",
  CAMERA_EXPOSURE_AREA_CHANGED = "cameraExposureAreaChanged",
  AUDIOMIXINGFINISHED = "audiomixingfinished",
  AUDIO_MIXING_FINISHED = "audioMixingFinished",
  AUDIO_MIXING_STATE_CHANGED = "audioMixingStateChanged",
  AUDIOEFFECTFINISHED = "audioeffectfinished",
  AUDIO_EFFECT_FINISHED = "audioEffectFinished",
  FIRST_REMOTE_AUDIO_DECODED = "firstRemoteAudioDecoded",
  VIDEODEVICESTATECHANGED = "videodevicestatechanged",
  VIDEO_DEVICE_STATE_CHANGED = "videoDeviceStateChanged",
  LOCAL_VIDEO_STATE_CHANGED = "localVideoStateChanged",
  VIDEOSIZECHANGED = "videosizechanged",
  VIDEO_SIZE_CHANGED = "videoSizeChanged",
  REMOTE_VIDEO_STATE_CHANGED = "remoteVideoStateChanged",
  USERENABLELOCALVIDEO = "userenablelocalvideo",
  USER_ENABLE_LOCAL_VIDEO = "userEnableLocalVideo",
  STREAMMESSAGEERROR = "streammessageerror",
  STREAM_MESSAGE_ERROR = "streamMessageError",
  MEDIA_ENGINE_LOAD_SUCCESS = "mediaEngineLoadSuccess",
  USER_SUPER_RESOLUTION_ENABLED = "userSuperResolutionEnabled",
  CHANNEL_MEDIA_RELAY_STATE_CHANGED = "channelMediaRelayStateChanged",
  CHANNEL_MEDIA_RELAY_STATE = "channelMediaRelayState",
  CHANNEL_MEDIA_RELAY_EVENT = "channelMediaRelayEvent",
  FIRSTLOCALAUDIOFRAME = "firstlocalaudioframe",
  FIRST_LOCAL_AUDIO_FRAME = "firstLocalAudioFrame",
  FIRST_LOCAL_AUDIO_FRAME_PUBLISHED = "firstLocalAudioFramePublished",
  FIRST_REMOTE_AUDIO_FRAME = "firstRemoteAudioFrame",
  RTMP_STREAMING_STATE_CHANGED = "rtmpStreamingStateChanged",

  STREAM_PUBLISHED = "streamPublished",
  STREAM_UNPUBLISHED = "streamUnpublished",
  TRANSCODING_UPDATED = "transcodingUpdated",
  AUDIO_ROUTE_CHANGED = "audioRouteChanged",
  LOCAL_PUBLISH_FALLBACK_TO_AUDIO_ONLY = "localPublishFallbackToAudioOnly",
  REMOTE_SUBSCRIBE_FALLBACK_TO_AUDIO_ONLY = "remoteSubscribeFallbackToAudioOnly",
  REMOTE_AUDIO_TRANSPORT_STATS = "remoteAudioTransportStats",
  REMOTE_VIDEO_TRANSPORT_STATS = "remoteVideoTransportStats",
  MICROPHONE_ENABLED = "microphoneEnabled",
  CONNECTION_STATE_CHANGED = "connectionStateChanged",
  NETWORK_TYPE_CHANGED = "networkTypeChanged",
  LOCAL_USER_REGISTERED = "localUserRegistered",
  USER_INFO_UPDATED = "userInfoUpdated",
  UPLOAD_LOG_RESULT = "uploadLogResult",

  STREAM_MESSAGE = "streamMessage",
  READY_TO_SEND_METADATA = "readyToSendMetadata",
  METADATA_RECEIVED = "metadataReceived",

  JOIN_CHANNEL_SUCCESS = "joinChannelSuccess",
  MEDIA_DEVICE_CHANGED = "mediaDeviceChanged",
  INTRA_REQUEST_RECEIVED = "intraRequestReceived",
  UPLINK_NETWORK_INFO_UPDATED = "uplinkNetworkInfoUpdated",
  DOWNLINK_NETWORK_INFO_UPDATED = "downlinkNetworkInfoUpdated",
  VIDEO_SOURCE_FRAME_SIZE_CHANGED = "videoSourceFrameSizeChanged",
  FACE_POSITION_CHANGED = "facePositionChanged",
  AUDIO_ROUTING_CHANGED = "audioRoutingChanged",
  AUDIO_SESSION_RESTRICTION_RESUME = "audioSessionRestrictionResume",
  ENCRYPTION_ERROR = "encryptionError",
  PERMISSION_ERROR = "permissionError",
  EXTENSION_EVENT = "extensionEvent",
  EXTENSION_STARTED = "extensionStarted",
  EXTENSION_STOPPED = "extensionStopped",
  EXTENSION_ERRORED = "extensionErrored",
  USER_ACCOUNT_UPDATED = "userAccountUpdated",
}
