import { SimpleTypeKind } from '@agoraio-extensions/cxx-parser';

module.exports = {
  'agora::rtc::IRtcEngine.getScreenCaptureSources': {
    name: 'agora::rtc::ScreenCaptureSourceInfo',
    source: 'agora::rtc::ScreenCaptureSourceInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.getVersion': {
    name: 'agora::rtc::ext::SDKBuildInfo',
    source: 'agora::rtc::ext::SDKBuildInfo*',
    kind: SimpleTypeKind.pointer_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IAudioDeviceManager.getPlaybackDeviceInfo': {
    name: 'agora::rtc::ext::AudioDeviceInfo',
    source: 'agora::rtc::ext::AudioDeviceInfo*',
    kind: SimpleTypeKind.pointer_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IAudioDeviceManager.getRecordingDeviceInfo': {
    name: 'agora::rtc::ext::AudioDeviceInfo',
    source: 'agora::rtc::ext::AudioDeviceInfo*',
    kind: SimpleTypeKind.pointer_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IAudioDeviceManager.enumeratePlaybackDevices': {
    name: 'agora::rtc::ext::AudioDeviceInfo',
    source: 'agora::rtc::ext::AudioDeviceInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IAudioDeviceManager.enumerateRecordingDevices': {
    name: 'agora::rtc::ext::AudioDeviceInfo',
    source: 'agora::rtc::ext::AudioDeviceInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IVideoDeviceManager.enumerateVideoDevices': {
    name: 'agora::rtc::ext::VideoDeviceInfo',
    source: 'agora::rtc::ext::VideoDeviceInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IVideoDeviceManager.numberOfCapabilities': {
    name: 'int',
    source: 'int',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserverBase.onRecordAudioFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserverBase.onPublishAudioFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserverBase.onPlaybackAudioFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserverBase.onMixedAudioFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserverBase.onEarMonitoringAudioFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserverBase.onPlaybackAudioFrameBeforeMixing': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioFrameObserver.onPlaybackAudioFrameBeforeMixing': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onCaptureVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onPreEncodeVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onSecondaryCameraCaptureVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onSecondaryPreEncodeCameraVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onScreenCaptureVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onPreEncodeScreenVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onMediaPlayerVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onSecondaryScreenCaptureVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onSecondaryPreEncodeScreenVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onRenderVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoFrameObserver.onTranscodedVideoFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioSpectrumObserver.onLocalAudioSpectrum': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioSpectrumObserver.onRemoteAudioSpectrum': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoEncodedFrameObserver.onEncodedVideoFrameReceived': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IVideoEncodedFrameObserver.OnEncodedVideoFrameReceived': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::media::IAudioPcmFrameSink.onFrame': {
    name: 'void',
    source: 'void',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
  'agora::rtc::IMusicContentCenter.isPreloaded': {
    name: 'bool',
    source: 'bool',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: true,
  },
};
