parsers:
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/IAgoraMediaComponentFactory.h'

  - name: AddNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      customHeaderFileNamePrefix: 'Custom'
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/*.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/custom_headers/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/time_utils.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtc_4.3.0/include/IAgoraMediaComponentFactory.h'

  - name: RemoveNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      configJsonFilePath: ./remove_node_list.json
  - name: PointerToArrayParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      ignoreDefaultRegex: false
      handleSameName: true
      configJsonFilePath: ./pointer_to_array.json
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      config: ./rename_member_function_param_type_list.ts
  - name: ReturnTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      config: ./assign_simple_type_list.ts
      convertReturnToVoid: false
  - name: FixEnumConstantParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      skipCalValue: true
  - name: MergeNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      config: ./merge_node_list.ts
  - name: OrderNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      parserDefaultValue: true
      config: ./update_simple_type_list.ts

defines_macros:
  - __ELECTRON__

renderers:
  - path: ../impl.ts

version: 4.3.0
