import { SimpleType, SimpleTypeKind } from '@agoraio-extensions/cxx-parser';
import {
  UpdateNodeConfig,
  updateSimpleTypeName,
} from '@agoraio-extensions/terra_shared_configs';

module.exports = {
  'agora::media::IAudioSpectrumObserver.onRemoteAudioSpectrum.spectrums@type': {
    name: 'agora::media::UserAudioSpectrumInfo',
    source: 'const agora::media::UserAudioSpectrumInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IMediaStreamingSourceObserver.onMetaData.data@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onWarning.warn@type': {
    name: 'agora::WARN_CODE_TYPE',
    source: 'agora::WARN_CODE_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onError.err@type': {
    name: 'agora::ERROR_CODE_TYPE',
    source: 'agora::ERROR_CODE_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandlerEx.onAudioQuality.quality@type': {
    name: 'agora::rtc::QUALITY_TYPE',
    source: 'agora::rtc::QUALITY_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onAudioDeviceStateChanged.deviceType@type':
    {
      name: 'agora::rtc::MEDIA_DEVICE_TYPE',
      source: 'agora::rtc::MEDIA_DEVICE_TYPE',
      kind: SimpleTypeKind.value_t,
      is_const: false,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onAudioDeviceStateChanged.deviceState@type':
    {
      name: 'agora::rtc::MEDIA_DEVICE_STATE_TYPE',
      source: 'agora::rtc::MEDIA_DEVICE_STATE_TYPE',
      kind: SimpleTypeKind.value_t,
      is_const: false,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onVideoDeviceStateChanged.deviceType@type':
    {
      name: 'agora::rtc::MEDIA_DEVICE_TYPE',
      source: 'agora::rtc::MEDIA_DEVICE_TYPE',
      kind: SimpleTypeKind.value_t,
      is_const: false,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onVideoDeviceStateChanged.deviceState@type':
    {
      name: 'agora::rtc::MEDIA_DEVICE_STATE_TYPE',
      source: 'agora::rtc::MEDIA_DEVICE_STATE_TYPE',
      kind: SimpleTypeKind.value_t,
      is_const: false,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onMediaDeviceChanged.deviceType@type': {
    name: 'agora::rtc::MEDIA_DEVICE_TYPE',
    source: 'agora::rtc::MEDIA_DEVICE_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandlerEx.onNetworkQuality.txQuality@type': {
    name: 'agora::rtc::QUALITY_TYPE',
    source: 'agora::rtc::QUALITY_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandlerEx.onNetworkQuality.rxQuality@type': {
    name: 'agora::rtc::QUALITY_TYPE',
    source: 'agora::rtc::QUALITY_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onLastmileQuality.quality@type': {
    name: 'agora::rtc::QUALITY_TYPE',
    source: 'agora::rtc::QUALITY_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onApiCallExecuted.err@type': {
    name: 'agora::ERROR_CODE_TYPE',
    source: 'agora::ERROR_CODE_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandlerEx.onStreamMessage.data@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandlerEx.onStreamMessageError.code@type': {
    name: 'agora::ERROR_CODE_TYPE',
    source: 'agora::ERROR_CODE_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onStreamPublished.error@type': {
    name: 'agora::ERROR_CODE_TYPE',
    source: 'agora::ERROR_CODE_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandler.onChannelMediaRelayStateChanged.state@type':
    {
      name: 'agora::rtc::CHANNEL_MEDIA_RELAY_STATE',
      source: 'agora::rtc::CHANNEL_MEDIA_RELAY_STATE',
      kind: SimpleTypeKind.value_t,
      is_const: false,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onChannelMediaRelayStateChanged.code@type':
    {
      name: 'agora::rtc::CHANNEL_MEDIA_RELAY_ERROR',
      source: 'agora::rtc::CHANNEL_MEDIA_RELAY_ERROR',
      kind: SimpleTypeKind.value_t,
      is_const: false,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onChannelMediaRelayEvent.code@type': {
    name: 'agora::rtc::CHANNEL_MEDIA_RELAY_EVENT',
    source: 'agora::rtc::CHANNEL_MEDIA_RELAY_EVENT',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEventHandlerEx.onAudioVolumeIndication.speakers@type':
    {
      name: 'agora::rtc::AudioVolumeInfo',
      source: 'const agora::rtc::AudioVolumeInfo*',
      kind: SimpleTypeKind.array_t,
      is_const: true,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onFacePositionChanged.vecRectangle@type':
    {
      name: 'agora::rtc::Rectangle',
      source: 'const agora::rtc::Rectangle*',
      kind: SimpleTypeKind.array_t,
      is_const: true,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngineEventHandler.onFacePositionChanged.vecDistance@type': {
    name: 'int',
    source: 'const int*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IMediaPlayerSourceObserver.onMetaData.data@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ext::IRtcEngine.createDataStream.config@type': {
    name: 'DataStreamConfig',
    source: 'const DataStreamConfig&',
    kind: SimpleTypeKind.reference_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.sendStreamMessage.data@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.startScreenCapture.mediaProjectionPermissionResultData@type':
    {
      name: 'uint8_t',
      source: 'const uint8_t*',
      kind: SimpleTypeKind.pointer_t,
      is_const: true,
      is_builtin_type: false,
    },
  'agora::rtc::IRtcEngine.setLogFilter.filter@type': {
    name: 'agora::commons::LOG_FILTER_TYPE',
    source: 'agora::commons::LOG_FILTER_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.enableInEarMonitoring.includeAudioFilters@type': {
    name: 'agora::rtc::EAR_MONITORING_FILTER_TYPE',
    source: 'agora::rtc::EAR_MONITORING_FILTER_TYPE',
    kind: SimpleTypeKind.value_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.queryCodecCapability.codec_info@type': {
    name: 'CodecCapInfo',
    source: 'CodecCapInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.queryCodecCapability.codecInfo@type': {
    name: 'CodecCapInfo',
    source: 'CodecCapInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.startDirectCdnStreaming.eventHandler@type': {
    name: 'IDirectCdnStreamingEventHandler',
    source: 'const IDirectCdnStreamingEventHandler*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeAudioBlocklist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeAudioBlacklist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeAudioAllowlist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeAudioWhitelist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeVideoBlocklist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeVideoBlacklist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeVideoAllowlist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setSubscribeVideoWhitelist.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setHighPriorityUserList.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngine.setAdvancedAudioOptions.options@type': {
    name: 'AdvancedAudioOptions',
    source: 'const AdvancedAudioOptions&',
    kind: SimpleTypeKind.reference_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ext::IRtcEngineEx.createDataStreamEx.config@type': {
    name: 'DataStreamConfig',
    source: 'const DataStreamConfig&',
    kind: SimpleTypeKind.reference_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.sendStreamMessageEx.data@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeAudioBlocklistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeAudioBlacklistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeAudioAllowlistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeAudioWhitelistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeVideoBlocklistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeVideoBlacklistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeVideoAllowlistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setSubscribeVideoWhitelistEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IRtcEngineEx.setHighPriorityUserListEx.uidList@type': {
    name: 'uid_t',
    source: 'const uid_t*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IMediaEngine.pullAudioFrame.frame@type': {
    name: 'IAudioFrameObserver::AudioFrame',
    source: 'const IAudioFrameObserver::AudioFrame*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IMediaEngine.pushAudioFrame.frame@type': {
    name: 'IAudioFrameObserver::AudioFrame',
    source: 'const IAudioFrameObserver::AudioFrame*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IMediaEngine.pushCaptureAudioFrame.frame@type': {
    name: 'IAudioFrameObserver::AudioFrame',
    source: 'const IAudioFrameObserver::AudioFrame*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IMediaEngine.pushReverseAudioFrame.frame@type': {
    name: 'IAudioFrameObserver::AudioFrame',
    source: 'const IAudioFrameObserver::AudioFrame*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IMediaEngine.pushDirectAudioFrame.frame@type': {
    name: 'IAudioFrameObserver::AudioFrame',
    source: 'const IAudioFrameObserver::AudioFrame*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IMediaEngine.pushVideoFrame.frame@type': {
    name: 'base::ExternalVideoFrame',
    source: 'const base::ExternalVideoFrame*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IMediaRecorder.setMediaRecorderObserver.callback@type': {
    name: 'media::IMediaRecorderObserver',
    source: 'const media::IMediaRecorderObserver*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.setZones.zones@type': {
    name: 'agora::rtc::SpatialAudioZone',
    source: 'const agora::rtc::SpatialAudioZone*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPosition.position@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPosition.axisForward@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPosition.axisRight@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPosition.axisUp@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPositionEx.position@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPositionEx.axisForward@type':
    {
      name: 'float',
      source: 'const float*',
      kind: SimpleTypeKind.array_t,
      is_const: true,
      is_builtin_type: false,
    },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPositionEx.axisRight@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ILocalSpatialAudioEngine.updateSelfPositionEx.axisUp@type': {
    name: 'float',
    source: 'const float*',
    kind: SimpleTypeKind.array_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::IMusicContentCenterEventHandler.onMusicChartsResult.result@type':
    {
      name: 'agora::rtc::MusicChartInfo',
      source: 'const agora::rtc::MusicChartInfo*',
      kind: SimpleTypeKind.array_t,
      is_const: true,
      is_builtin_type: false,
    },
  'agora::rtc::IMusicContentCenter.getCaches.cacheInfo@type': {
    name: 'agora::rtc::MusicCacheInfo',
    source: 'agora::rtc::MusicCacheInfo*',
    kind: SimpleTypeKind.array_t,
    is_const: false,
    is_builtin_type: false,
  },
  'agora::rtm::IStreamChannel.publishTopicMessage.message@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::VideoCanvas.priv@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::ThumbImageBuffer.buffer@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::base::ExternalVideoFrame.buffer@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::media::IAudioFrameObserverBase::AudioFrame.buffer@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtc::VideoCompositingLayout.appData@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtm::JoinTopicOptions.meta@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
  'agora::rtm::IRtmEventHandler::MessageEvent.message@type': {
    name: 'uint8_t',
    source: 'const uint8_t*',
    kind: SimpleTypeKind.pointer_t,
    is_const: true,
    is_builtin_type: false,
  },
};
