name: Build Addon
run-name: ${{ github.actor }} triggered this job
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Build type'
        required: true
        default: 'sdk'
        type: choice
        options:
          - demo
          - sdk
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          curl -X POST -sS -D- -o/dev/null ${{secrets.JENKINS_BUILD_URL}} -H 'Content-Type: application/json' -d '{"branch":"${{github.ref_name}}"}'
