name: Update dependencies

on:
  workflow_dispatch:
    inputs:
      dependencies-content:
        description: The content of dependencies
        required: true
        type: string

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update dependencies
        id: dep
        uses: AgoraIO-Extensions/actions/.github/actions/dep@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          target-branch: ${{ github.ref_name }}
          dependencies-content: ${{ inputs.dependencies-content }}          
          target-files: |
            package.json
