name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Increment "major", "minor", "patch", or "pre*" version; or specify version [default: "patch"]'
        required: true
        default: 'patch'
        type: string
      dry-run:
        description: 'Do not touch or write anything, but show the commands'
        default: true
        type: boolean
      publish-npm:
        description: 'publish npm'
        default: true
        type: boolean

jobs:
  release-it:
    if: ${{ inputs.publish-npm }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup NPM auth token
        run: |
          npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: Dry Run Release
        if: ${{ inputs.dry-run }}
        run: |
          yarn release ${{ inputs.increment }} -d --ci

      - name: NPM Publish
        if: ${{ !inputs.dry-run }}
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          yarn release ${{ inputs.increment }} --ci --no-git.tag --no-github.release --npm.allowSameVersion

  update-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update Example
        if: ${{ !inputs.dry-run }}
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          yarn example add ${{steps.package-info.outputs.name}}@${{ inputs.increment }}

      - name: Commit Example
        if: ${{ !inputs.dry-run }}
        run: |
          git add example
          git commit -m "chore(example): update example to install agora-electron-sdk@${{ inputs.increment }}"

      - name: Release
        if: ${{ !inputs.dry-run }}
        run: |
          yarn release ${{ inputs.increment }} --ci --no-npm --no-git.commit
