name: Publish to NPM
run-name: ${{ github.actor }} triggered this job
on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Increment "major", "minor", "patch", or "pre*" version; or specify version [default: "patch"]'
        required: true
        default: 'patch'
        type: string
      dry-run:
        description: 'Do not touch or write anything, but show the commands'
        default: true
        type: boolean

jobs:
  release-it:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup NPM auth token
        run: |
          npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}

      - name: Dry Run Release
        if: ${{ inputs.dry-run }}
        run: |
          yarn release ${{ inputs.increment }} -d --ci

      - name: Release
        if: ${{ !inputs.dry-run }}
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          yarn release ${{ inputs.increment }} --ci --no-git.tag --no-github.release

      - name: Get Package Info
        id: package-info
        run: |
          echo ::set-output name=name::$(node -p "require('./package.json').name")
          echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: Update Example
        run: |
          yarn example install ${{steps.package-info.outputs.name}}@${{steps.package-info.outputs.version}}

      - name: Commit Example
        run: |
          git add example
          git commit -m "chore(example): update example to install ${{steps.package-info.outputs.name}}@${{steps.package-info.outputs.version}}"
      
      - name: Release
        run: |
          yarn release ${{ inputs.increment }} --ci --no-npm